### ISSUE TITLE
Pod Install Error

### ISSUE THREAD

**Issue by git-xbits** [ja2375/add_2_calendar#11]
When i try to run my code in IOS, this error show:
> [!] Unable to determine Swift version for the following pods:
> 
> - `add_2_calendar` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

Another 10 plugins I have in my project install normally, just ass_2_calendar break.

flutter doctor -v:

[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale pt-BR)
    • Flutter version 1.2.1 at /Users/xbitssoftware/Documents/flutter
    • Framework revision 8661d8aecd (5 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[!] Android toolchain - develop for Android devices (Android SDK version 27.0.3)
    • Android SDK at /Users/xbitssoftware/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    ✗ Flutter requires Android SDK 28 and the Android BuildTools 28.0.3
      To update using sdkmanager, run:
        /Users/xbitssoftware/Library/Android/sdk/tools/bin/sdkmanager "platforms;android-28" "build-tools;28.0.3"
      or visit https://flutter.io/setup/#android-setup for detailed instructions.
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.0.beta.2

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • iPad Pro (12.9-inch) (2nd generation) • CDB69D98-8D89-4CF9-8729-9CD1AC2476E2 • ios • iOS 11.0 (simulator)

! Doctor found issues in 1 category.

No errors in windows.

I have in podfile the tags for Swift:

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

**Comment by git-xbits** [comment]
Problem resolved including 'SWIFT_VERSION = 4.0;' in every PRODUCT_NAME = "$(TARGET_NAME)"; from my /ios/Runner.xcodeproj/project.pbxproj
EG:
PRODUCT_NAME = "$(TARGET_NAME)";
				SWIFT_VERSION = 4.0; #####
				TARGETED_DEVICE_FAMILY = "1,2";
				VERSIONING_SYSTEM = "apple-generic";

**Comment by santiagoalmeidabolannos** [comment]
I got this after adding the 'SWIFT_VERSION = 4.0;' in every PRODUCT_NAME = "$(TARGET_NAME)";

`Xcode's output:
↳
    warning: The iOS Simulator deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.4.99. (in target 'Flutter')
    warning: The iOS Simulator deployment target is set to 4.3, but the range of supported deployment target versions for this platform is 8.0 to 12.4.99. (in target 'FMDB')
    geolocator-faqvxlvlcxdhxmgbindtwaezblzq
    /Users/mauer/development/flutter/.pub-cache/hosted/pub.dartlang.org/add_2_calendar-1.3.0/ios/Classes/Add2CalendarPlugin.m:2:9: fatal error: 'add_2_calendar/add_2_calendar-Swift.h' file not found
    #import <add_2_calendar/add_2_calendar-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    Runner-aohckdbncvggbmgabbdaejwmiyge
    note: Using new build systemnote: Planning buildnote: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone X.`
