### ISSUE TITLE
Android Gradle plugin requires 1.5.20 Kotlin Gradle plugin version

### ISSUE THREAD

**Issue by wryczko** [ja2375/add_2_calendar#110]
When using 'com.android.tools.build:gradle:7.3.1' and higher I get following error:

The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':add_2_calendar' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

It works fine with com.android.tools.build:gradle:7.2.2

**Comment by rsetkus** [comment]
:+1:

**Comment by aragonet** [comment]
Apparently the change has been made and for 8 months the [PR Upgrade/android #102 ](https://github.com/ja2375/add_2_calendar/pull/102) has been merged but no version has been uploaded to pub.dev

Hope they do it soon 🙏

**Comment by Rodrigossff91** [comment]
When I run in debbug it even works more in release it doesn't work

**Comment by diegogarciar** [comment]
Just released a new version on pub.dev, can you try it out?

**Comment by wryczko** [comment]
It works now, thanks.
