### ISSUE TITLE
Location and description optional

### ISSUE THREAD

**Issue by aaumond** [ja2375/add_2_calendar#111]
Hi,

Is it possible to make the description and location fields optional?
I tried to create a branch on your repository to make a pull request but it was impossible.

Thanks in advance.

**Comment by aaumond** [comment]
Another small question. I see that on the master branch, it is possible to add a URL on an iOS event. But unfortunately, when I get the add_2_calendar dependency directly from pub.dev, the URL parameter is not available. Has the version been released?

**Comment by diegogarciar** [comment]
I will create a release later today, thanks for your PR
