### ISSUE TITLE
App crashes on location autocomplete

### ISSUE THREAD

**Issue by GunesYurdakul** [ja2375/add_2_calendar#113]
When you start editing the location(trigger the location autocomplete), the application crashes. NSContactsUsageDescription is required for Location autocomplete. I think it was always required as you can see in this post: https://stackoverflow.com/questions/48593627/eventkit-error-when-an-instance-of-ekeventeditviewcontroller-presented-then-a

It would be better if you could add the NSContactsUsageDescription requirement to your documentation on pub.dev.

**Comment by diegogarciar** [comment]
Sounds like a great idea, will do!
