### ISSUE TITLE
Open Calendar in Releases 

### ISSUE THREAD

**Issue by Rodrigossff91** [ja2375/add_2_calendar#114]
Error in releases, in the debbugger version the calendar opens normally but when I generate a release version the calendar does not open

Has anyone ever experienced this

**Comment by diegogarciar** [comment]
can you try with version 2.2.0?

**Comment by Rodrigossff91** [comment]
Of course I will try now

**Comment by Rodrigossff91** [comment]
looks like the problem was my phone
my work friends' cell phones are opening normally
