### ISSUE TITLE
Ios Crash after calling createEvent

### ISSUE THREAD

**Issue by JustinWeru12** [ja2375/add_2_calendar#116]
The package worked great until i upgraded to the latest build. It works fine on android.
 This is the log result
`Could not cast value of type 'NSNull' (0x7ff863f30558) to 'NSString' (0x7ff863f2cf98).`
Here is the result of Flutter Doctor.
`[✓] Flutter (Channel stable, 3.3.7, on macOS 13.0 22A380 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.73.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability`

Here is the code 
`import 'package:add_2_calendar/add_2_calendar.dart';

class CreateCalendar {
  final String? eventTitle, eventdesc;
  final DateTime? eventstartdate, eventenddate;

  CreateCalendar(
      {this.eventTitle,
      this.eventdesc,
      this.eventstartdate,
      this.eventenddate});

  createEvent() {
    final Event event = Event(
        title: eventTitle!,
        description: eventdesc!,
        startDate: eventstartdate!,
        endDate: eventenddate!,
        iosParams: const IOSParams());
    Add2Calendar.addEvent2Cal(event);
  }
}
`

**Comment by blaneyneil** [comment]
as a hack in the meantime, just add a url for IOSParams, like so:

```
iosParams: IOSParams(
          url: 'https://mysite.com', // was crashing w/o this after 2.2.0
          //reminder: null,
),
```

it's crashing upon a null string for url, so just give it something.

**Comment by diegog-sf** [comment]
Thanks, will post a fix soon

**Comment by diegogarciar** [comment]
2.2.1 should be available shortly!
