### ISSUE TITLE
Android Issue with location

### ISSUE THREAD

**Issue by NachtaktiverHalbaffe** [ja2375/add_2_calendar#118]
When I want to add an Event to calendar with the optional field location, it overwrites/gets written to description field in calendar. Basically cant get a variable passed to the location field. My Event which i pass to myy calendar:

```dart
var event = Event(
                title: freizeit.name,
                description: freizeit.description,
                // also happens without string interpolation
                location:
                    "${freizeit.location.adress}, ${freizeit.location.street}, ${freizeit.location.postalCode}",
                startDate: freizeit.startDate,
                endDate: freizeit.endDate,
              );
```

Some build infos:
Flutter version: 3.3.8 (stable)
add_2_calendar_version: 2.2.1
Android compiler settings: compiledVersion and targetversion 33 (also happened on other versions)
Testet on: Android 11, 12 and 13(on emulator)

**Comment by Phobie53** [comment]
Same issue for me

**Comment by martin-geidobler** [comment]
This issue still exists and I haven't seen a comment about it...
Can this pretty please be fixed?

**Comment by martin-geidobler** [comment]
@diegogarciar kind of an urgent issue though, basically non-functional for android at this time

**Comment by martin-geidobler** [comment]
<img width="562" alt="image" src="https://user-images.githubusercontent.com/48251866/204022480-429b150a-b695-4dfc-ad31-73fce1e862fe.png">
found the issue for you (:

**Comment by Stef-GMS** [comment]
This shows merged.  Does it close this issue?

**Comment by NachtaktiverHalbaffe** [comment]
Sorry, was a little busy in the past. Thought the maintainer would close it after merge/fix. Thanks for the fix and everything works now. Great work! 

I close this issue
