### ISSUE TITLE
Android Opens the Calendar while adding event.

### ISSUE THREAD

**Issue by SreeAnir** [ja2375/add_2_calendar#12]
Adding an event to the default calendar is working.But, in case of android, the calendar app is opened and asks user to save the date.How about saving the events to the calendar without opening the calendar app ?

**Comment by ja2375** [comment]
Hello, 
For the time being i don't have time to implement this.
I think it is a good idea to open the calendar app to inform the user about what he is doing. But if you think it would be better not doing so, you can implement it yourself and send a PR :)
