### ISSUE TITLE
presentCalendarModalToAddEvent need a default switch case.

### ISSUE THREAD

**Issue by FelippeNO** [ja2375/add_2_calendar#127]
At the new version of Swift, it says that the “switch must be exhaustive” on presentCalendarModalToAddEvent func at the SwiftAdd2CalendarPlugin class, on Swift.

**Comment by Mind-Reaper** [comment]
I have the same issue

**Comment by FelippeNO** [comment]
For now, you can fix it adding default case to the func. I already have sent a PR.

**Comment by Mind-Reaper** [comment]
I forked your PR. It works perfectly. Thanks

**Comment by diegogarciar** [comment]
Thanks for raising this, 2.2.4 was just released

**Comment by maximeFlave** [comment]
Hi ! Version 2.2.4 with fix is deployed on pub.dev ?

**Comment by diegog-sf** [comment]
Thanks for the callout, i thought i deployed but it seems it didn't. I'll try again

**Comment by diegogarciar** [comment]
deployed!
