### ISSUE TITLE
Unable to bridge NSNumber to Int erro in 32 bit iphone

### ISSUE THREAD

**Issue by huzhiren** [ja2375/add_2_calendar#13]
I got this error when running in iPhone 4S:

Fatal error: Unable to bridge NSNumber to Int: file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-1001.0.69.5/swift/stdlib/public/SDK/Foundation/NSNumber.swift, line 375

in SwiftAdd2CalendarPlugin.swift line 30:

        addEventToCalendar(title: title, description: desc, location: location, startDate: Date(milliseconds: (args["startDate"] as! Int)), endDate: Date(milliseconds: (args["endDate"] as! Int)), allDay: args["allDay"] as! Bool, completion: { (success) -> Void in

A safe guess is that the args startDate and endDate is bigger than Int can hold in 32 bit machine.

**Comment by ja2375** [comment]
I updated the plugin on pub to include the recent pull request fix for this issue. Please upgrade to 1.3.0 and it should be fixed. Apologies for the wait.
