### ISSUE TITLE
Google Play policy violation caused by targeting Android 11 (API level 31)

### ISSUE THREAD

**Issue by SarunasDaubaris** [ja2375/add_2_calendar#132]
### Issue description

On August 11th, our Flutter app received a warning "App must target Android 13 (API level 33) or higher" from Google Play. Because of the violation, our app won't be able to upload updates to Google Play: "From Nov 1, 2023, if your target API level is not within 1 year of the latest Android release, you won't be able to update your app.".

Our app targets Android API level 33, but this library targets API level 31.

Please update the library Android target to API level 33 so the library users wouldn't receive this Google Play warning.

### Flutter doctor summary
[!] Flutter (Channel stable, 3.10.6, on macOS 13.4 22F66 darwin-arm64 (Rosetta),
    locale en-LT)
    ! Warning: `dart` on your path resolves to
      /opt/homebrew/Cellar/dart/2.19.5/libexec/bin/dart, which is not inside
      your current Flutter SDK checkout at /Users/sarunas/fvm/versions/3.10.6.
      Consider adding /Users/sarunas/fvm/versions/3.10.6/bin to the front of
      your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.77.1)
[✓] Connected device (2 available)            
[✓] Network resources

### App build.gradle
        minSdkVersion 23
        targetSdkVersion 33

### Library version used
2.1.1

Android target API level 31 can be seen in master: https://github.com/ja2375/add_2_calendar/blob/master/android/build.gradle

**Comment by nilsreichardt** [comment]
You shouldn't be blocked by Google Play because of this library. You only need to make sure that **all** your tracks have a version where you set your target API level to 33. Most of the time you have an old and closed track with a version, which has not target API level 33.
