### ISSUE TITLE
Adding event without launching calendar application

### ISSUE THREAD

**Issue by LaurensB235** [ja2375/add_2_calendar#134]
Hi, the ReadMe contains the following:

```
The plugin doesn't need any special permissions by default to add events to the calendar. However, events can also be added without launching the calendar application, for this it is needed to add calendar permissions to your AndroidManifest.xml
```

How do you use this feature? I added the permissions to my manifest, but it still opens the application and I don't see a way to do this. Sorry if this is a stupid question, maybe I am just overlooking something.

**Comment by sunjiaming** [comment]
I would like that support, too

**Comment by raheeldev05** [comment]
I also want to achieve this, without opening calendar app.

**Comment by LaurensB235** [comment]
I found an alternative, [device_calendar](https://pub.dev/packages/device_calendar). Closing this issue

**Comment by Lainaaa** [comment]
> I found an alternative, [device_calendar](https://pub.dev/packages/device_calendar). Closing this issue

I am not able to use library because of [this issue](https://github.com/builttoroam/device_calendar/issues/496), so in my opinion you issue is still actual.
