### ISSUE TITLE
SWIFT_VERSION attribute

### ISSUE THREAD

**Issue by AdrianJCo** [ja2375/add_2_calendar#14]
`add_2_calendar` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod

**Comment by ja2375** [comment]
Simply add Swift support to your project. That should be enough...
Please refer to other issues for more info.

**Comment by fignealberto** [comment]
Trying v1.3.0 with other issues solutions (flutter create -i swift, add swift file to project) but issues persists;

Unable to determine Swift version for the following pods:
    - `add_2_calendar` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set

Any thoughts? Thanks in advance

**Comment by ja2375** [comment]
@fignealberto Please check if #11 solution helps you

**Comment by fignealberto** [comment]
@ja2375 solve the problem starting a fresh project with flutter create -i swift and then copying previous code into this new project. Thank you
