### ISSUE TITLE
Execution failed for task ':add_2_calendar:compileReleaseJavaWithJavac'

### ISSUE THREAD

**Issue by shivraj-walke-bbi** [ja2375/add_2_calendar#145]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':add_2_calendar:compileReleaseJavaWithJavac'.
> error: invalid source release: 17

**Comment by diegogarciar** [comment]
have you tried version 3.0.1?

**Comment by shivraj-walke-bbi** [comment]
Hello,

I have tried version 2.2.5 on xcode 15 , but I have error occurred then revert my version to 2.2.3, then it’s work.

Thanks,
Regards,

Shivraj Walke
Software Developer

Börm Bruckmeier Infotech India Pvt. Ltd.
Plot No. 552, Sector No. 28, PCNTDA
Nigdi, Pune - 411044

e-mail   ***@***.******@***.***>



From: Diego Garcia ***@***.***>
Date: Wednesday, 25 October 2023 at 8:11 PM
To: ja2375/add_2_calendar ***@***.***>
Cc: Shivraj Walke | Börm Bruckmeier Infotech ***@***.***>, Author ***@***.***>
Subject: Re: [ja2375/add_2_calendar] Execution failed for task ':add_2_calendar:compileReleaseJavaWithJavac' (Issue #145)

have you tried version 3.0.1?

**Comment by shivraj-walke-bbi** [comment]
I have tried version 2.2.5 on xcode 15 , but I have error occurred then revert my version to 2.2.3, then it’s work.

**Comment by jacobdedman** [comment]
I'm having the same issue. I've been using 2.2.4, but I need the iOS 17 support from 2.2.5, and I'm currently using Flutter 3.10 (Dart 3.0.6) so I can't upgrade to 3.0.0 yet. When I upgraded to 2.2.5 iOS builds fine, but android errors out with this the same error: invalid source release: 17

Is there any fix for this other than upgrading flutter to be able to use 3.0.0?

**Comment by MuhamadJalal** [comment]
The same error here!

`* What went wrong:`
`Execution failed for task ':add_2_calendar:compileReleaseJavaWithJavac'.`
`> error: invalid source release: 17`

Anyone has solved it?

**Comment by jacobdedman** [comment]
> The same error here!
> 
> `* What went wrong:` `Execution failed for task ':add_2_calendar:compileReleaseJavaWithJavac'.` `> error: invalid source release: 17`
> 
> Anyone has solved it?

@MuhamadJalal The only thing I got to work was upgrading from flutter 3.10 to flutter 3.13 so that I could use add_2_calendar version 3.0.0 or higher. Probably not the answer you were hoping for, but I hope this helps!

**Comment by MuhamadJalal** [comment]
> > The same error here!
> > `* What went wrong:` `Execution failed for task ':add_2_calendar:compileReleaseJavaWithJavac'.` `> error: invalid source release: 17`
> > Anyone has solved it?
> 
> @MuhamadJalal The only thing I got to work was upgrading from flutter 3.10 to flutter 3.13 so that I could use add_2_calendar version 3.0.0 or higher. Probably not the answer you were hoping for, but I hope this helps!

@jacobdedman 

I found a solution [here](https://github.com/ja2375/add_2_calendar/issues/141#issuecomment-1774058741) without upgrading (old project...a lot of dependencies!)
