### ISSUE TITLE
iOS bug 'add_2_calendar/add_2_calendar-Swift.h' file not found

### ISSUE THREAD

**Issue by hahahhaczzcz** [ja2375/add_2_calendar#27]
iOS bug    'add_2_calendar/add_2_calendar-Swift.h' file not found

**Comment by ja2375** [comment]
Does your project have Swift support? If not, please add it. Otherwise, look for other closed issues in this repo.

I'm not able to help as you are not giving me much info.

If you still need more help, reopen the issue and include more info, like your flutter version, exception stack trace...

**Comment by hahahhaczzcz** [comment]
<img width="1141" alt="截屏2019-11-28上午9 16 54" src="https://user-images.githubusercontent.com/22882188/69769447-d77de800-11bf-11ea-9e12-940893795d0e.png">

<img width="562" alt="截屏2019-11-28上午9 18 31" src="https://user-images.githubusercontent.com/22882188/69769512-0eec9480-11c0-11ea-8b0f-f5484ad60a4f.png">

**Comment by hahahhaczzcz** [comment]
How can I have Swift support ? What I need to do?

**Comment by hahahhaczzcz** [comment]
<img width="652" alt="截屏2019-11-28上午9 51 19" src="https://user-images.githubusercontent.com/22882188/69770646-d69b8500-11c4-11ea-896b-a4699e42a14f.png">

i don`t found out a File Name 'add_2_calendar-Swift.h' in the whole project.
