### ISSUE TITLE
Not working for iOS

### ISSUE THREAD

**Issue by jgadjetx** [ja2375/add_2_calendar#3]
Error Given:

![screenshot 2018-12-23 at 00 17 00](https://user-images.githubusercontent.com/8150242/50379102-259d7980-0648-11e9-99ec-d768ffddf6d2.png)

**Comment by ja2375** [comment]
Are you using the lastest version of the plugin? That exception only made sense when the iOS part of the plugin was not implemented, but it is actually...

**Comment by jgadjetx** [comment]
Yeah

in my pubsec.yaml

dependencies:
 add_2_calendar: ^1.0.2  

Works on android but not iOS

**Comment by ja2375** [comment]
That's weird. Code is implemented for iOS as well. I've just checked everything is all right and there are no typos...
Can i see the rest of the exception stack trace?

**Comment by jgadjetx** [comment]
![screenshot 2018-12-23 at 01 33 19](https://user-images.githubusercontent.com/8150242/50379455-d01a9a00-0652-11e9-912f-cff4269c4645.png)

**Comment by ja2375** [comment]
That is not the exception stack trace.
The stack trace is where you got the MissingPluginException.

Also please send me your method where the exception is thrown.

**Comment by jgadjetx** [comment]
![screenshot 2018-12-24 at 01 38 19](https://user-images.githubusercontent.com/8150242/50388362-ab8af480-071c-11e9-8870-15bc1f36a468.png)

**Comment by jgadjetx** [comment]
When I run for the first time without "entering the app"

**Comment by jgadjetx** [comment]
![screenshot 2018-12-27 at 02 34 23](https://user-images.githubusercontent.com/8150242/50460575-f8bad080-097f-11e9-9359-b75ff07200a2.png)

**Comment by ja2375** [comment]
I know where you get the exception but it certainly is not missing. The videos there. You can look for it.

I have one more question for you: did you ex cute flutter run targeting the iOS platform since you added the plugin to your pubspec? Please note that just a hot reload/hot restart is not enough to fully register the plugin on the platform.
