### ISSUE TITLE
Issue with adding attendees.

### ISSUE THREAD

**Issue by prabhunath111** [ja2375/add_2_calendar#31]
Can you please tell me how to add attendees?

**Comment by lrebscher** [comment]
Hello, I checked the code and adding attendees is currently not implemented.

**Comment by prabhunath111** [comment]
> Hello, I checked the code and adding attendees is currently not implemented.
> Duplicate of #16

Can you please add the code for adding attendees?

**Comment by diegogarciar** [comment]
This feature has been aded for Android in the latest release
