### ISSUE TITLE
Can't open Calendar on Web

### ISSUE THREAD

**Issue by AndroidNils** [ja2375/add_2_calendar#32]
If I try to use this plugin with Flutter Web, I get an exception on calling `Add2Calendar.addEvent2Cal(event)`:

`
:53796/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:109648 Overflow on channel: flutter.javih.com/add_2_calendar.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
`

`
Uncaught (in promise) Error: MissingPluginException(No implementation found for method add2Cal on channel flutter.javih.com/add_2_calendar)
    at Object.throw_ [as throw] (:53796/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:4025)
    at MethodChannel._invokeMethod (:53796/packages/flutter/src/gestures/arena.ddc.js:5840)
    at _invokeMethod.next (<anonymous>)
    at onValue (:53796/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:42353)
    at _RootZone.runUnary (:53796/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:42239)
    at _FutureListener.thenAwait.handleValue (:53796/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:38003)
    at handleValueCallback (:53796/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:38503)
    at Function._propagateToListeners (:53796/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:38535)
    at _Future.new.[_completeWithValue] (:53796/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:38397)
    at async._AsyncCallbackEntry.new.callback (:53796/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:38414)
    at Object._microtaskLoop (:53796/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:42452)
    at _startMicrotaskLoop (:53796/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:42458)
    at :53796/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:38738
DartError @ :53796/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:5322
throw_ @ :53796/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:4025
_invokeMethod @ :53796/packages/flutter/src/gestures/arena.ddc.js:5840
onValue @ :53796/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:42353
runUnary @ :53796/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:42239
handleValue @ :53796/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:38003
handleValueCallback @ :53796/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:38503
_propagateToListeners @ :53796/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:38535
[_completeWithValue] @ :53796/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:38397
(anonymous) @ :53796/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:38414
_microtaskLoop @ :53796/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:42452
_startMicrotaskLoop @ :53796/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:42458
(anonymous) @ :53796/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:38738
`

**Flutter doctor**
[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.15.2 19C57, locale de-DE)
    • Flutter version 1.14.6 at /usr/local/Caskroom/flutter/latest/flutter
    • Framework revision fabeb2a16f (3 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/nils/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /Users/nils/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (3 available)
    • BKL L09    • 192.168.0.143:5555 • android-arm64  • Android 9 (API 28)
    • Chrome     • chrome             • web-javascript • Google Chrome 79.0.3945.130
    • Web Server • web-server         • web-javascript • Flutter Tools

**Comment by ja2375** [comment]
This plugin has no support for web as there is no default calendar on that platform.

I'm closing this. If you want to discuss this topic, please reopen.
