### ISSUE TITLE
[iOS] status bar change color after close the calendar

### ISSUE THREAD

**Issue by Kiruel** [ja2375/add_2_calendar#34]
When I open the `Add2Calendar.addEvent2Cal` then cancel or add to the calendar. The status bar change and the text of the status bar become white.

I try to change the color after the event is set to the calendar but the Future do not wait until the event is success or fail.

It's happen only on iOS. I test on simulation and iPhone XR.

Before:
![Screenshot 2020-03-02 at 18 16 40](https://user-images.githubusercontent.com/8250175/75700253-11282880-5cb2-11ea-9f8d-bfb09d0f3e6e.png)

After:
![Screenshot 2020-03-02 at 18 16 58](https://user-images.githubusercontent.com/8250175/75700276-19806380-5cb2-11ea-97ac-24d8597765aa.png)

EDIT:
It's only happen when I change the `AppBar` brightness to `Brightness.light`

**Comment by olivierkastel** [comment]
Same issue for me

**Comment by Kiruel** [comment]
I fix the problem here https://github.com/ja2375/add_2_calendar/pull/35  waiting for merge :) @olivierkastel

**Comment by ja2375** [comment]
Merged :)
