### ISSUE TITLE
App (iOS) crashes when description or location is null

### ISSUE THREAD

**Issue by nilsreichardt** [ja2375/add_2_calendar#37]
## Problem
App crashes when description or location is null (Event object).

## Code to reproduce 
```
onPressed: () {
   final calendarEvent = Event(
      startDate: DateTime(2020, 1, 1, 9),
      endDate: DateTime(2020, 1, 1, 10),
      title: "Title",
      description: null,
      location: null,
   );
  add_2_calendar.Add2Calendar.addEvent2Cal(calendarEvent);
},
```

Run this code with iOS.

**Comment by AndroidNils** [comment]
@ja2375 Any updates?

**Comment by diegogarciar** [comment]
With null-safety it is now not possible to enter null as an argument for description or location

**Comment by diegogarciar** [comment]
To not use them, simply do not include them while creating `Event`
