### ISSUE TITLE
Timezone off by one hour on Android Version of app

### ISSUE THREAD

**Issue by jshepin** [ja2375/add_2_calendar#40]
In my android app when I set the GMT timezone, it's off by an hour, so, for example, I live in central time (gmt-5), I set it to gmt-6 and its correct, otherwise its off by an hour. I can verify that its not device settings because I needed to compensate an hour on my personal device and on the simulator which are different manufacturers and software version of Android, so it's definitely now my device's problem However on my ios app version, something is different and it works at the correct timezone, no compensation necessary. I can simply use a ternary operator whether its ios or not, however, I'm wondering the cause behind this and if its a bug or what. If I don't set a timezone it's completely off altogether. I don't know why the timezone has to be manually either.

**Comment by alwan93** [comment]
Im not sure how it goes for you, but mine working properly after I add the timezone. I did it like this.
timeZone: 'GMT+8',

**Comment by castrovictor** [comment]
I am having the same problem when I run it with my android phone. It works fine with the android emulator. Any solution?

**Comment by castrovictor** [comment]
I found a solution: there is some issue with the standards to name timezones. Use [flutter native timezone package](https://pub.dev/packages/flutter_native_timezone) to get the timezone without issues.
