### ISSUE TITLE
Localization of EventUIKit Interface on iOS devices 

### ISSUE THREAD

**Issue by Dshosev** [ja2375/add_2_calendar#41]
Hej Folks,

maybe i just don't get it, but if I open the widget for adding events on iOS the interface is always in English, regardless the device language.
Is it possible to localise this? My Flutter app is only on German, so I don't localise any other Strings.
If it's not possible to localise the widget yet, I think this would be a great enhancement.

Best Regards!
![IMG_2A5FA537F111-1](https://user-images.githubusercontent.com/36865345/81398181-00b88200-9129-11ea-96e7-7926ef3f583c.jpeg)

**Comment by ltoenjes** [comment]
Were you able to get it to work? If so: How?

**Comment by diegogarciar** [comment]
@ltoenjes duplicate of #50 solution posted there
