### ISSUE TITLE
SDK location not found. when release, but debug it work

### ISSUE THREAD

**Issue by center12** [ja2375/add_2_calendar#42]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'add_2_calendar'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

The plugin add_2_calendar could not be built due to the issue above.

**Comment by melvinm99** [comment]
same here

**Comment by NikitaMasev** [comment]
I have the same problem.

**Comment by juzo** [comment]
No update on this?

"The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility."

**Comment by trunghieuvn** [comment]
i have same as issue

**Comment by hebahsaleh** [comment]
same issue.. any solution??

**Comment by micmdk** [comment]
any solutions or suggestions/temp fixes for this one?

**Comment by Goldy98** [comment]
Same issue ! Did someone found a workaround ?

**Comment by diegogarciar** [comment]
Have you migrated to V2?

**Comment by Goldy98** [comment]
Here's the current line in my pubsec.yml file : `add_2_calendar: ^2.0.1`

**Comment by diegogarciar** [comment]
I mean on Android do you have v2 embedding in your AndroidManifest?

**Comment by Goldy98** [comment]
Yes sir 
`<meta-data android:name="flutterEmbedding" android:value="2" />`

**Comment by diegogarciar** [comment]
Thank you for the information, I'll have a look tomorrow morning!

**Comment by Goldy98** [comment]
Maybe it's something about **Graddle** version. My project current graddle version is **4.0.1**

**Comment by diegogarciar** [comment]
Are you building your project for release? or if anything else, can you perform the same action with the example project?

**Comment by Goldy98** [comment]
I'm trying to run **`flutter run --release`**. Everything works fine when i am in debug mode `**flutter run --debug**`

**Comment by diegogarciar** [comment]
Were you able to run `flutter run --release` on the example project? I had no problem

**Comment by Goldy98** [comment]
Hi! I finally upgraded my project Graddle version to the latest one and everything is working fine now. Thank for your attention

**Comment by diegogarciar** [comment]
I'm glad you made it work!
I'm closing this for now as it seems is not an issue with the package itself. If someone knows or finds out how to make the package compatible with older Gradle versions, please submit a new issue or a PR.
