### ISSUE TITLE
Is it necessary to take permissions to contacts?

### ISSUE THREAD

**Issue by kleyos** [ja2375/add_2_calendar#48]
Hey guys. Could you please explain why we need this permission 
```
<key>NSContactsUsageDescription</key>
<string>INSERT_REASON_HERE</string>
```

**Comment by Dominik-Schoen** [comment]
I tried it without this permission and it worked in the simulator (14.3).

**Comment by diegogarciar** [comment]
true, documentation will be updated accordingly, thank you!
