### ISSUE TITLE
Plugin always returns success on iOS

### ISSUE THREAD

**Issue by theneedyguy** [ja2375/add_2_calendar#5]
It would be nice for the plugin to ask the user again for permission to add to calendar when he tries to trigger the "add to calendar"-event. At least on iOS. I know it just works on Android but the iOS implementation will never ask the user again (unless you reinstall the app). It will also always get a positive success state when the user declined the permission which is weird.

**Comment by theneedyguy** [comment]
Just looked up the problem. Apparently you cannot ask the user again for permission. Still the problem with the success state being positive persists. To replicate: try to add an event on iOS, deny permission, snackbar will still report a success.

**Comment by ja2375** [comment]
Yes, I've seen it. Will try to fix ASAP.

**Comment by theneedyguy** [comment]
Thank you, friend. I like your plugin and will use it in my app as soon as this little bug is fixed! Keep it going, the world needs people like you. If you have a place to accept donations I will happily do so 👍

**Comment by ja2375** [comment]
Fixed this :)
Please let me know if it works for you now.

As for the donation, i do have paypal but never set it up for accepting donations. Thank you anyway :)

**Comment by theneedyguy** [comment]
Perfect, it worked. Also the All-Day feature is a good addition. Thank you for your work!
