### ISSUE TITLE
Language Support

### ISSUE THREAD

**Issue by Crypt0Graphic** [ja2375/add_2_calendar#50]
It's default English. Other languages or customization would be good.

**Comment by diegogarciar** [comment]
Hello, the plugin will use phone's system language, is it behaving differently?

**Comment by diegogarciar** [comment]
Hi, I found the issue, you must set in your info.plist a key named Localizations and specify your supported languages

<img width="580" alt="Screen Shot 2021-03-17 at 9 14 55 a m" src="https://user-images.githubusercontent.com/17276155/111500482-465ab980-8701-11eb-953f-4895ecb3b5f4.png">

**Comment by Crypt0Graphic** [comment]
I resolved it but how i forgot, sorry. Probably same way. Thanks.

**Comment by diegogarciar** [comment]
Sure, sorry for late response, will add this to documentation.
