### ISSUE TITLE
Flutter IOS build failed

### ISSUE THREAD

**Issue by gauravdv** [ja2375/add_2_calendar#51]
- [ **dependencies: add_2_calendar: ^1.4.0** ]

_`*** BUILD FAILED **

fatal error : module 'add_2_calendar' not found
@import add_2_calendar;
1 error generated.`_

![flutter_ios_build_failed](https://user-images.githubusercontent.com/41941592/103091682-f517be00-461a-11eb-8762-1b4b44cc09c8.png)

We download the dependency and add manually into folder also, but it does not work.

**version using in my project :**

`[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.7 19H2, locale en-IN)
   • Flutter version 1.20.4 at /Users/manicpod/Downloads/flutter
   • Framework revision fba99f6cf9 (3 months ago), 2020-09-14 15:32:52 -0700
   • Engine revision d1bc06f032
   • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
   • Android SDK at /Users/manicpod/Library/Android/sdk
   • Platform android-30, build-tools 30.0.0
   • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
   • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
   • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
   • Xcode at /Applications/Xcode.app/Contents/Developer
   • Xcode 12.3, Build version 12C33
   • CocoaPods version 1.10.0`

>

**Comment by SpencerRiddering** [comment]
Possible cause? https://github.com/flutter/flutter/issues/43986#issuecomment-747903097

**Comment by diegogarciar** [comment]
@gauravdv were you able to fix the problem?

**Comment by diegogarciar** [comment]
Closing this as no further info was provided, if you are still experiencing the issue, please let me know
