### ISSUE TITLE
timezones

### ISSUE THREAD

**Issue by hermabritz** [ja2375/add_2_calendar#52]
Hi.

Can anyone assist with the format of the time zones?

Thanks,

**Comment by nilsreichardt** [comment]
You can use this package: https://pub.dev/packages/flutter_native_timezone

**Comment by Djamel96** [comment]
You can use this function : 

`addEventToCallender() {
 // ofsset is your current timezone offset (like +6 for GMT+6)
  int offset = DateTime.now().timeZoneOffset.inHours;
  String timeZone = offset > 0 ? '+' + offset.toString() : offset.toString();
  final Event calendarevent = Event(
      title:  title,
      description:  description ,
      location: "location",
      startDate:  startday,
      endDate:  endTime,
      timeZone: "GMT$timeZone");
  Add2Calendar.addEvent2Cal(calendarevent);
}`

**Comment by hermabritz** [comment]
Good day,

 

Thank you very much.

 

//Herman
