### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by nilsreichardt** [ja2375/add_2_calendar#53]
## Description
All dependencies are migrated to null safety. So we should migrate this package to null safety.

## Resources
* [How to migrate Dart packages to null safety](https://youtu.be/eBr5tlumwlg)
* [Announcing Dart null safety beta](https://medium.com/dartlang/announcing-dart-null-safety-beta-87610fee6730)

**Comment by nilsreichardt** [comment]
I created a PR: #54

**Comment by kw2019ltd** [comment]
..

**Comment by ja2375** [comment]
Merged. Many thanks for the contribution!
