### ISSUE TITLE
Create multiple events

### ISSUE THREAD

**Issue by erperejildo** [ja2375/add_2_calendar#55]
How could I create multiples events at once? For example for birthday reminders

**Comment by erperejildo** [comment]
any help?

**Comment by diegogarciar** [comment]
I don't think it is possible, as the api makes you confirm the event on the actual calendar

**Comment by erperejildo** [comment]
> I don't think it is possible, as the api makes you confirm the event on the actual calendar

But natively (at least on Android) we can create 3 different kinds of events:

<img width="125" alt="Screenshot 2021-03-16 at 00 54 57" src="https://user-images.githubusercontent.com/5629919/111369321-373f2180-8697-11eb-9310-90479426a952.png">

Is it no possible to create reminders instead of events then?

**Comment by diegogarciar** [comment]
Thank you for the image:
The feature is not currently implemented. I looked trough android's docs and I think there's no such thing for iOS. This makes it an android only feature and this plugin  is intended to provide same functionality to all platforms. For this reason I don't believe it will be implemented in the future either.

**Comment by erperejildo** [comment]
I see. Well, thanks anyway for the info

**Comment by diegogarciar** [comment]
It seems reminders are part of event, and without them we cannot add an alarm to an event, I'll keep looking around if there's something we can add as it would be good to add them to Android side too, please let me know if you find a solution for this.

**Comment by diegogarciar** [comment]
Hello @erperejildo I just released v2.0.1, with it you can call `Add2Calendar.addEvent2Cal(event, androidNoUI: true)`, this will not show the calendar UI so I think you can add multiple events at once. Also with this option reminders do work on Android.
Hopes this helps with your app!

**Comment by erperejildo** [comment]
Thanks for the quick changes. I'll try it out and I'll let you know asap

**Comment by EinatK** [comment]
> Hello @erperejildo I just released v2.0.1, with it you can call `Add2Calendar.addEvent2Cal(event, androidNoUI: true)`, this will not show the calendar UI so I think you can add multiple events at once. Also with this option reminders do work on Android.
> Hopes this helps with your app!

I don't see this implemented. Added the latest version

**Comment by diegogarciar** [comment]
Actually I had to remove it as it seemed it needed [more work](https://github.com/ja2375/add_2_calendar/pull/64#issuecomment-826125011).  

The code is [this one](https://github.com/ja2375/add_2_calendar/blob/4aa0658abf011da71fa2a67ed086e9fea79617a5/android/src/main/java/com/javih/add2calendar/Add2CalendarPlugin.java#L181), but as I mention in the PR, we need to add code to get the calendar ID, allow the user to select one if there are multiple, and then use that ID to perform the requests. If you could help me with the feature I would greatly appreciate it.

**Comment by erperejildo** [comment]
> Actually I had to remove it as it seemed it needed [more work](https://github.com/ja2375/add_2_calendar/pull/64#issuecomment-826125011).
> 
> The code is [this one](https://github.com/ja2375/add_2_calendar/blob/4aa0658abf011da71fa2a67ed086e9fea79617a5/android/src/main/java/com/javih/add2calendar/Add2CalendarPlugin.java#L181), but as I mention in the PR, we need to add code to get the calendar ID, allow the user to select one if there are multiple, and then use that ID to perform the requests. If you could help me with the feature I would greatly appreciate it.

any update?

**Comment by diegogarciar** [comment]
I dont have the android background to develop this feature, Any help on this would be greatly appreciated.

**Comment by shahryar-cmyk** [comment]
If you are using it for only the birthday reminder I think it would be great to use local schedule notification. Here is an example that might help.
https://github.com/TomerPacific/BirthdayCalendar

**Comment by diegogarciar** [comment]
Hey, I think `device_calendar` might be a better fit for your needs.
