### ISSUE TITLE
Flutter 2.0 : Add2CalendarPlugin.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by deacon78** [ja2375/add_2_calendar#56]
Hello

Flutter : 2.0
add_2_calendar: 1.4.0

Since the update in Flutter 2.0, I got this message when compiling :

`Running Gradle task 'assembleRelease'...                        
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\add_2_calendar-1.4.0\android\src\main\java\com\javih\add2calendar\Add2CalendarPlugin.java uses or overrides a deprecated API.

Note: Recompile with -Xlint:deprecation for details.`

**Comment by dcarriola** [comment]
I'm also having the same issue, I can't even compile it on Android because of that.

I'm running:
* Flutter v.2.0.2
* add_2_calendar v.2.0.0

**Comment by diegogarciar** [comment]
Version 2.0 was just released from a PR, I’ll have a look but might take a couple of days, PRs are welcome in the meantime. You can always use the previous version while theres a fix

**Comment by deacon78** [comment]
Hello
Same issue with 2.0.1 : 
C:\flutter\.pub-cache\hosted\pub.dartlang.org\add_2_calendar-2.0.1\android\src\main\java\com\javih\add2calendar\Add2CalendarPlugin.java uses or overrides a deprecated API.

**Comment by diegogarciar** [comment]
I checked the file, the only deprecated api I could find is this:
```
/**
     * backward compatibility with embedding v1
     **/
    public static void registerWith(Registrar registrar) {
        Add2CalendarPlugin plugin = new Add2CalendarPlugin();
        plugin.activity = registrar.activity();
        plugin.context = registrar.context();
        plugin.setupMethodChannel(registrar.messenger());
    }

```
which as you can see is for backwards compatibility, I think you can disregard the message for now as we want to maintain backwards compatibility.

**Comment by dcarriola** [comment]
I re-created the Android folder and added the user-permissions again, using v 2.0.1 it didn't complain about that deprecated API. I also had to change the min-sdk version to 16 instead of 18.

**Comment by diegogarciar** [comment]
So that's in the example project right? this means that the plugin itself is working as expected?

**Comment by diegogarciar** [comment]
I now ignore the v1 compatibility warning via `@SuppressWarnings("deprecation")`. Issue should disappear now. Closing this
