### ISSUE TITLE
Android 11 not handled : PlatformException(not_available,` No email clients found!, null, null)

### ISSUE THREAD

**Issue by deacon78** [ja2375/add_2_calendar#61]
Hello

I got this error only on Android 11 (API 30) virtual device on Android Studio : 
`PlatformException(not_available,` No email clients found!, null, null)`
The GMAIL client is already set up on the virtual device.

I do not reproduce on other devices (virtual or not) which are Android 10 or less (API 29 or less)

**Comment by diegogarciar** [comment]
can you share your code?

**Comment by deacon78** [comment]
Of course ^^

`try {
        final Email email = Email(
          body: "some content",
          subject: "some subject",
          recipients: [''],
          attachmentPaths: [somefile.path],
          isHTML: false,
        );

        await FlutterEmailSender.send(email);
        debugPrint('email sent correctly');
      }
      catch (e) {
        debugPrint('error sending email');
        print(e);
      }`

**Comment by deacon78** [comment]
My code works with any android version, expect on an Android 11 virtual device (Android virtual device) :-(

**Comment by deacon78** [comment]
Sorry it was not your package :(
