### ISSUE TITLE
Why does this plugin need to access device contacts?

### ISSUE THREAD

**Issue by joseucarvajal** [ja2375/add_2_calendar#62]
Most Calendar packages I've found out there require this permission:

```
<key>NSCalendarsUsageDescription</key>
<string>INSERT_REASON_HERE</string>
```

But why **add_2_calendar** requires device contacts access on iOS?

```
<key>NSContactsUsageDescription</key>
<string>INSERT_REASON_HERE</string>
```

**Comment by joseucarvajal** [comment]
> Most Calendar packages I've found out there require this permission:
> 
> ```
> <key>NSCalendarsUsageDescription</key>
> <string>INSERT_REASON_HERE</string>
> ```
> 
> But why **add_2_calendar** requires device contacts access on iOS?
> 
> ```
> <key>NSContactsUsageDescription</key>
> <string>INSERT_REASON_HERE</string>
> ```

It seems is a typo in the Flutter package documentation.

**Comment by diegogarciar** [comment]
Thank you, we will update the pub.dev docs soon

**Comment by diegogarciar** [comment]
Contacts permissions are not required, it is the calendar permission the one that's needed

**Comment by diegogarciar** [comment]
Thanks for the heads up. Documentation has been updated.

**Comment by andrewescutia** [comment]
I will note that if the 'Invitees' option is selected from the native iOS event dialog, then the app will crash unless NSContactsUsageDescription is specified.

**Comment by GunesYurdakul** [comment]
When you start editing the location(trigger the location autocomplete), the application crashes. NSContactsUsageDescription is required for Location autocomplete. I think it was always required as you can see in this post: https://stackoverflow.com/questions/48593627/eventkit-error-when-an-instance-of-ekeventeditviewcontroller-presented-then-a

It would be better if you could add the `NSContactsUsageDescription` requirement back to your documentation on pub.dev.
