### ISSUE TITLE
Feature request: Create a recurring repeating event

### ISSUE THREAD

**Issue by andraskende** [ja2375/add_2_calendar#63]
Would it be possible to add recurring events ?

Thank you !

![cal1](https://user-images.githubusercontent.com/23754/115172136-6f13fd00-a079-11eb-84ee-9b6e34da14f2.png)
![cal2](https://user-images.githubusercontent.com/23754/115172140-6fac9380-a079-11eb-91b5-0e0f665d5ebe.png)

**Comment by diegogarciar** [comment]
Hello, thanks for the suggestion, it is in the roadmap but currently there are no plans for implementing it in the near future. However if you send me a working example on how to implement it (Android side) I can speed things up to release it.

**Comment by andraskende** [comment]
Hello,

I was able to modify the plugin to add RRULE

add_2_calendar:
    path: ./add_2_calendar

basic example worked on my local:

https://github.com/ja2375/add_2_calendar/blob/master/android/src/main/java/com/javih/add2calendar/Add2CalendarPlugin.java#L123
intent.putExtra(CalendarContract.Events.RRULE, "FREQ=YEARLY");

https://github.com/ja2375/add_2_calendar/blob/master/android/src/main/java/com/javih/add2calendar/Add2CalendarPlugin.java#L156
values.put(CalendarContract.Events.RRULE, "FREQ=YEARLY");

(I could modify more to pass variables...

Also might need change dtend to duration on recurring events:
https://developer.android.com/reference/android/provider/CalendarContract.Events.html

Insert
- dtend if the event is non-recurring
- duration if the event is recurring


Thank you,
Andras

**Comment by diegogarciar** [comment]
nice, can you create a PR with your changes?

**Comment by andraskende** [comment]
Created Pull request: https://github.com/ja2375/add_2_calendar/pull/64

Thank you !!

**Comment by diegogarciar** [comment]
merged #64
