### ISSUE TITLE
Feature request: Open Google calendar on iOS

### ISSUE THREAD

**Issue by Add00w** [ja2375/add_2_calendar#65]
I want to use google calendar but ios automatically opens on apple calendar what should I do to use google calendar?

**Comment by diegogarciar** [comment]
It is currently not possible with this package. I don’k know if its even possible natively. If you find an easy way to do this natively please share the resources and I could add the functionality

**Comment by diegogarciar** [comment]
Closing this as there are no plans to implement this and at this point it doesn't seem possible. If you find a way, feel free to submit a PR
