### ISSUE TITLE
Add2CalendarPlugin.java uses or overrides a deprecated API

### ISSUE THREAD

**Issue by Ben-Thum** [ja2375/add_2_calendar#66]
Hi,
I tried to run the example but got this message:

add_2_calendar-2.1.0\android\src\main\java\com\javih\add2calendar\Add2CalendarPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

Any ideas on how to resolve this?

Thanks!
Ben

**Comment by diegogarciar** [comment]
Hello, this is just a warning, for compatibility with v1 embedding, your code should run just fine.

**Comment by Ben-Thum** [comment]
Hi Diego,

Thanks for your quick response. The problem is my AVD. I did a Cold Boot and it works well.

Awesome plugin!

Cheers,
Ben

**Comment by diegogarciar** [comment]
Your welcome, I'll close this issue for now then.
