### ISSUE TITLE
Effecting other libraries

### ISSUE THREAD

**Issue by hamzali4642** [ja2375/add_2_calendar#71]
When I add add_2_calendar to my pubspec.yaml file, my cloud firestore throwing exception in release mode. in debug mode its working properly. If any one else facing this issue and you have solved this issue then please share your solution here. I will really appreciate this.

exception:  [cloud_firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying
 with a backoff.

**Comment by diegogarciar** [comment]
Have you tried flutter clean? I have never experienced the issue and I publish regularly to the stores

**Comment by hamzali4642** [comment]
> Have you tried flutter clean? I have never experienced the issue and I publish regularly to the stores

yeah I have tried but nothing changed

**Comment by hamzali4642** [comment]
I downgrade firestore version and its work.
