### ISSUE TITLE
A problem was found with the configuration of task ':add_2_calendar:checkDebugManifest' (type 'CheckManifest').

### ISSUE THREAD

**Issue by ettiennelr** [ja2375/add_2_calendar#72]
* What went wrong:
A problem was found with the configuration of task ':add_2_calendar:checkDebugManifest' (type 'CheckManifest').
  - In plugin 'com.android.build.gradle.api.AndroidBasePlugin' type 'com.android.build.gradle.internal.tasks.CheckManifest' property 'manifest' has @Input annotation used on property of type 'File'.

Gradle 7.1.1
------------------------------------------------------------

Build time:   2021-07-02 12:16:43 UTC
Revision:     774525a055494e0ece39f522ac7ad17498ce032c

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          1.8
OS:           Mac OS X 11.4 x86_64

**Comment by diegogarciar** [comment]
Hello, I don't have the knowledge to fix the issue, if you find a fix, please let me know or create a PR

**Comment by diegogarciar** [comment]
I have migrated the package into a new template project, let me know if this solves your issue

**Comment by diegogarciar** [comment]
I'll close this issue for now as it is expected to be solved with the project redo, please feel free to reopen it if the issue still persists
