### ISSUE TITLE
Cant find podspec for IOS

### ISSUE THREAD

**Issue by LucaKnaup** [ja2375/add_2_calendar#74]
After adding the package, I tried to update my podspecs. I get the following error.

`[!] No podspec found for add_2_calendar in .symlinks/plugins/add_2_calendar/ios`

Thanks for help.

**Comment by diegogarciar** [comment]
can you try using flutter clean?

**Comment by LucaKnaup** [comment]
Oh, I didn't tried yet sorry. Worked for me. Thanks.
