### ISSUE TITLE
start bad behave in firebase project 

### ISSUE THREAD

**Issue by paras-28** [ja2375/add_2_calendar#77]
firebase api  literally not working after pub get add_2_calendar. auth works well 

cloud_firestore: ^2.4.0
firebase_core: ^1.4.0

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1110], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.6)
[!] Android Studio (not installed)
[√] IntelliJ IDEA Community Edition (version 2021.1)
[√] VS Code (version 1.56.2)
[√] Connected device (4 available)

**Comment by diegogarciar** [comment]
can you please explain what is not working?

**Comment by diegogarciar** [comment]
Hello, due to inactivity I'll close this issue, if you need further help, please comment below and I'll reopen the issue
