### ISSUE TITLE
flutter iOS compile error

### ISSUE THREAD

**Issue by SaxPlayer** [ja2375/add_2_calendar#8]
Added a simple button to test the process. Hot re-load in simulator worked but when hitting my button app crashed without any error in the console. Force quit app in the simulator and then started a new debug session. My app won't run, instead throwing the following:-

Launching lib/main.dart on iPhone XR in debug mode...
Xcode build done.                                            4.6s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    === BUILD TARGET video_player OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/andyclayton/.pub-cache/hosted/pub.dartlang.org/add_2_calendar-1.2.1/ios/Classes/SwiftAdd2CalendarPlugin.swift:55:31: warning: immutable value 'e' was never used; consider replacing with '_' or removing it
                      } catch let e as NSError? {
                                  ^
                                  _
    === BUILD TARGET video_player OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/andyclayton/.pub-cache/hosted/pub.dartlang.org/add_2_calendar-1.2.1/ios/Classes/Add2CalendarPlugin.m:2:9: fatal error: 'add_2_calendar/add_2_calendar-Swift.h' file not found
    #import <add_2_calendar/add_2_calendar-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
Could not build the application for the simulator.
Error launching application on iPhone XR.
Exited (sigterm)

**Comment by ja2375** [comment]
Your project seems to be missing Swift support. Please refer to issue #4 (in the closed section) to fix that problem.

**Comment by SaxPlayer** [comment]
Thank you for that. This is my first Flutter project and I wasn't aware of the -i swift flag. I'll follow the recommendations in that closed issue and see if works for me. I suspect it will, however I'll keep this open for a couple of days until I try. Thanks for your help!

**Comment by ja2375** [comment]
Sure. You're welcome! :)

**Comment by SaxPlayer** [comment]
Thank you. I've copied to a new Swift enabled project and copied by Dart files over and that's fixed the problem. Moving to Swift appears to break things with some other plugins, but those aren't related to this one so I'll close this issue. Thanks for your help.
