### ISSUE TITLE
Kotlin files

### ISSUE THREAD

**Issue by erperejildo** [ja2375/add_2_calendar#80]
Not sure how to describe this issue but I removed support for Kotlin in my app by performing these changes:
https://stackoverflow.com/questions/60258327/how-to-remove-kotlin-support-from-flutter-app

When I build only this package seems to be failing and despite I'm not sure about the issue, it points to some Kotlin files:

```
e: /Users/dani/development/flutter/.pub-cache/hosted/pub.dartlang.org/add_2_calendar-2.1.1/android/src/main/kotlin/com/javih/add_2_calendar/Add2CalendarPlugin.kt: (8, 28): Unresolved reference: NonNull
e: /Users/dani/development/flutter/.pub-cache/hosted/pub.dartlang.org/add_2_calendar-2.1.1/android/src/main/kotlin/com/javih/add_2_calendar/Add2CalendarPlugin.kt: (31, 38): Unresolved reference: NonNull
e: /Users/dani/development/flutter/.pub-cache/hosted/pub.dartlang.org/add_2_calendar-2.1.1/android/src/main/kotlin/com/javih/add_2_calendar/Add2CalendarPlugin.kt: (37, 32): Unresolved reference: NonNull
e: /Users/dani/development/flutter/.pub-cache/hosted/pub.dartlang.org/add_2_calendar-2.1.1/android/src/main/kotlin/com/javih/add_2_calendar/Add2CalendarPlugin.kt: (37, 59): Unresolved reference: NonNull
e: /Users/dani/development/flutter/.pub-cache/hosted/pub.dartlang.org/add_2_calendar-2.1.1/android/src/main/kotlin/com/javih/add_2_calendar/Add2CalendarPlugin.kt: (56, 40): Unresolved reference: NonNull

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
```

Shouldn't I see .java instead? Do you know why is it failing?

**Comment by diegogarciar** [comment]
This project was built in kotlin, is there a specific reason as to why you don't want to support Kotlin?

**Comment by erperejildo** [comment]
I need to work with some SDKs that don't support Kotlin at all and the MainActivity needs to be filled in with too many Java functions. I have tried to convert from Java to Kotlin using Android Studio but the conversion it's not ok and produces some errors.

My understanding of these 2 languages is zero so I was thinking to remove Kotlin to use the original Java functions without touching them and creating new errors because of this.

If you tell me that I need to use Kotlin I'd need to investigate more kind of conversions. I'd appreciate more info about this if you know other ways.

**Comment by diegog-sf** [comment]
Kotlin and java can execute together, you can just use java change your mainactivity to .java in your project and then allow kotlin on other packages (this).

If you still need to remove it, try using one of the last 2 previous releases, they were made in Java.

**Comment by diegogarciar** [comment]
Kotlin and java can execute together, you can just use java change your mainactivity to .java in your project and then allow kotlin on other packages (this).

If you still need to remove it, try using one of the last 2 previous releases, they were made in Java.
