### ISSUE TITLE
Error: editor placeholder in source file - Add2CalendarPlugin

### ISSUE THREAD

**Issue by SirEben** [ja2375/add_2_calendar#81]
Please I need help. I was trying to build an ios app on a simulator and I got this error below:

Launching lib/main.dart on iPhone 8 in debug mode...
Running Xcode build...
Xcode build done. 110.2s
Failed to build iOS app
Error output from Xcode build:
↳
** BUILD FAILED **

Xcode's output:
↳
Command CompileSwift failed with a nonzero exit code
Command CompileSwift failed with a nonzero exit code
Command CompileSwift failed with a nonzero exit code
/Users/USERNAME/Danny/flutter/.pub-cache/hosted/pub.dartlang.org/add_2_calendar-2.1.1/ios/Classes/SwiftAdd2CalendarPlugin.swift:121:13: error: editor placeholder in source file
<#fatalError()#>
^
/Users/Danny/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/add_2_calendar-2.1.1/ios/Classes/SwiftAdd2CalendarPlugin.swift:140:17: warning: setter for 'statusBarStyle' was deprecated in iOS 9.0: Use -[UIViewController preferredStatusBarStyle]
UIApplication.shared.statusBarStyle = UIStatusBarStyle.default
^
/Users/Danny/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/add_2_calendar-2.1.1/ios/Classes/SwiftAdd2CalendarPlugin.swift:150:13: warning: setter for 'statusBarStyle' was deprecated in iOS 9.0: Use -[UIViewController preferredStatusBarStyle]
UIApplication.shared.statusBarStyle = statusBarStyle
^
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 8.

**Comment by diegogarciar** [comment]
Hello, I looked trough the file and couldn't finde that placeholder, did you modifed the file by yourself?

Please try any of the following
1- run flutter clean
or 
2- go to that file, and delete <#fatalError()#> I don't recognize this line in the original code

**Comment by SirEben** [comment]
Thanks for the comment. Let me try the suggestions. I'll be back

**Comment by diegogarciar** [comment]
hey did it worked?

**Comment by diegogarciar** [comment]
I close this for now as it was fixed.
