### ISSUE TITLE
Error : Android release mode

### ISSUE THREAD

**Issue by filipe-syrox** [ja2375/add_2_calendar#82]
I am developing an app that uses add_2_calendar with webview_flutter and url_launcher.

On release mode the webview_flutter plugin fails to lunch the javascriptChannels call when having the add_2_calendar plugin added to the project.  Removing add_2_calendar plugin solves the issue, also when running on debug mode everything works as expected.

I am thinking there is some interference between the plugins but not sure why it would only occur in release mode.

Any help/ideas greatly appreciated.

**Comment by diegogarciar** [comment]
Hi, from what you are experiencing, it could be related to proguard obfuscation or optimization. But I wouldn't know the exact reason as to why or how to solve it.

**Comment by filipe-syrox** [comment]
completely forgot about obfuscation, turning it off solved the problem, thanks for your help.

**Comment by diegogarciar** [comment]
Awesome, closing!
