### ISSUE TITLE
Add event to google calendar , outlook or apple calendar.

### ISSUE THREAD

**Issue by dev-hussein** [ja2375/add_2_calendar#84]
I can't find a way to allow user to choose the app he want to add his event. 
So what i need i want to show bottom sheet with apps installed on the device that can used it to add calendar event {Google Calendar , ICalendar, Outlook  ... etc }

**Comment by diegogarciar** [comment]
This is not possible as it would require a custom integration for each calendar. Maybe you can create an calendar file and by opening it, the apps that can open calendar files will show.

**Comment by diegogarciar** [comment]
Closing this as currently it is out of the packages scope
