### ISSUE TITLE
Migrate to AndroidX

### ISSUE THREAD

**Issue by abc873693** [ja2375/add_2_calendar#9]
As title.
Android support library will deprecated.
Does migrate to AndroidX library?

**Comment by ja2375** [comment]
I will work on this. Thanks!

**Comment by ja2375** [comment]
Hello,
This project does not use the android support library. So there is nothing to update at all.
I am going to push a refactor of the whole project thought.

**Comment by abc873693** [comment]
OK, I understand.
Thank for your response.
