### ISSUE TITLE
How do I add events without opening the calendar

### ISSUE THREAD

**Issue by DioboKN** [ja2375/add_2_calendar#90]
How do I add events without opening the calendar

**Comment by pruidong** [comment]
I also encountered this problem.I have authorized to read and delete calendar events on my phone, but I still open the calendar every time I add an event.

**Comment by pruidong** [comment]
There is some progress here, but this feature was temporarily removed. 

https://github.com/ja2375/add_2_calendar/issues/55#issuecomment-855904050

**Comment by pruidong** [comment]
> I think device_calendar might be a better fit to your needs https://pub.dev/packages/device_calendar

Ok, thank you.
