### ISSUE TITLE
Flutter Web support

### ISSUE THREAD

**Issue by surveshoeb** [ja2375/add_2_calendar#91]
Do you have a plan to add web support in the near future?

**Comment by diegog-sf** [comment]
Hello, I'm not sure if we can tap device's calendar from the web, have you seen this functionality on other places?

**Comment by surveshoeb** [comment]
@diegog-sf not yet but if there is an option like this it will be great.

**Comment by diegogarciar** [comment]
Thanks for the suggestion, closing this for now as it’s currently not possible
