### ISSUE TITLE
Flutter 2.10 support required

### ISSUE THREAD

**Issue by SarunasDaubaris** [ja2375/add_2_calendar#94]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.2.1 21D62 darwin-arm, locale en-LT)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.62.3)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

When running `flutter pub get` with Flutter 2.10 SDK, the command prints out this error for `add_2_calendar` library:

`The plugin add_2_calendar requires your app to be migrated to the Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration and re-run this command.`

Please upgrade the library to support the 2.10 Flutter SDK.

**Comment by diegog-sf** [comment]
I was just able to run the example app, Not sure about the changes but I'll publish a new version to pub.dev

<img width="1741" alt="Screen Shot 2022-02-22 at 8 50 16 a m" src="https://user-images.githubusercontent.com/87551320/155168504-02861102-268c-4ab6-a2e9-bf30ef78f713.png">

**Comment by diegog-sf** [comment]
Just released 2.1.3, please try it out and let me know!

**Comment by SarunasDaubaris** [comment]
Hello. It is a warning. We'll test the new version and let you know. Thank you.

**Comment by diegogarciar** [comment]
Just tested this and it worked! Thanks for raising the issue
